# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Escarmoosh' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Escarmoosh
  pod 'Alamofire'

  target 'EscarmooshTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EscarmooshUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
