//
//  DisplayCardViewController.swift
//  Escarmoosh
//
//  Created by Arnaud Verrier on 21/01/2019.
//  Copyright (c) 2019 escarmoosh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DisplayCardDisplayLogic: class
{
    func displaySomething(viewModel: DisplayCard.Information.ViewModel)
}

class DisplayCardViewController: UIViewController, DisplayCardDisplayLogic
{
    var interactor: DisplayCardBusinessLogic?
    var router: (NSObjectProtocol & DisplayCardRoutingLogic & DisplayCardDataPassing)?
    
    @IBOutlet var cardInformation: GeneriqueCardInformationView!
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = DisplayCardInteractor()
        let presenter = DisplayCardPresenter()
        let router = DisplayCardRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        interactor.cardWorker = CardWorker(cardStore: CardFakker())
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomething()
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething()
    {
        let request = DisplayCard.Information.Request(id: "0")
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: DisplayCard.Information.ViewModel)
    {
        cardInformation.display(viewModel: viewModel)
    }
}

