//
//  DisplayCardPresenter.swift
//  Escarmoosh
//
//  Created by Arnaud Verrier on 21/01/2019.
//  Copyright (c) 2019 escarmoosh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DisplayCardPresentationLogic
{
    func presentInformation(response: DisplayCard.Information.Response)
}

class DisplayCardPresenter: DisplayCardPresentationLogic
{
    weak var viewController: DisplayCardDisplayLogic?
    
    // MARK: Do something
    
    func presentInformation(response: DisplayCard.Information.Response)
    {
        let completeName = response.card.firstName + " " + response.card.lastName
        let completeLocation = response.card.club
        let completeCategory = response.card.weapon + " - " + response.card.category
        let completeWeapon = response.card.hand + " - " + response.card.grip
        
        let viewModel = DisplayCard.Information.ViewModel(completeName: completeName, completeLocation: completeLocation, completeCategory: completeCategory, completeWeapon: completeWeapon, score: response.card.score)
        viewController?.displaySomething(viewModel: viewModel)
    }
}
