//
//  DisplayCardInteractor.swift
//  Escarmoosh
//
//  Created by Arnaud Verrier on 21/01/2019.
//  Copyright (c) 2019 escarmoosh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DisplayCardBusinessLogic
{
    func doSomething(request: DisplayCard.Information.Request)
}

protocol DisplayCardDataStore
{
    //var name: String { get set }
}

class DisplayCardInteractor: DisplayCardBusinessLogic, DisplayCardDataStore
{
    var presenter: DisplayCardPresentationLogic?
    var worker: DisplayCardWorker?
    
    var cardWorker: CardWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: DisplayCard.Information.Request)
    {
        cardWorker?.fetchCard(with: request.id, completionHandler: { (card:Card?, error:Error?) in
            
            if let card = card {
                
                let response = DisplayCard.Information.Response(card:card)
                self.presenter?.presentInformation(response: response)
            }
        })
    }
}

