//
// Card.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct CardModel: Codable {


    public var _id: String

    public var firstName: String

    public var lastName: String

    public var club: String

    public var birthday: Date

    public var category: String

    public var hand: String

    public var weapon: String

    public var grip: String
    
    public var score: Double

    public var competences: [CompetenceModel]
    
    public init(_id: String, firstName: String, lastName: String, club: String, birthday: Date, category: String, hand: String, weapon: String, grip: String, score: Double, competences: [CompetenceModel]) {
        self._id = _id
        self.firstName = firstName
        self.lastName = lastName
        self.club = club
        self.birthday = birthday
        self.category = category
        self.hand = hand
        self.weapon = weapon
        self.grip = grip
        self.competences = competences
        self.score = score
    }
    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case firstName
        case lastName
        case club
        case birthday
        case category
        case hand
        case weapon
        case grip
        case competences
        case score
    }

}
