//
// Card.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct Card: Codable {


    public var _id: String

    public var firstName: String

    public var lastName: String

    public var club: String

    public var birthday: Date

    public var category: String

    public var hand: String

    public var weapon: String

    public var grip: String

    public var card: [Competence]?
    public init(_id: String, firstName: String, lastName: String, club: String, birthday: Date, category: String, hand: String, weapon: String, grip: String, card: [Competence]?) { 
        self._id = _id
        self.firstName = firstName
        self.lastName = lastName
        self.club = club
        self.birthday = birthday
        self.category = category
        self.hand = hand
        self.weapon = weapon
        self.grip = grip
        self.card = card
    }
    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case firstName
        case lastName
        case club
        case birthday
        case category
        case hand
        case weapon
        case grip
        case card
    }

}
