//
// Competence.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct Competence: Codable {

    public enum Label: String, Codable { 
        case attaque = "Attaque"
        case defense = "Defense"
    }
    public var _id: String
    public var label: Label

    /** card score for this competence &#x3D; Sum(Skill.score)  */
    public var score: BigDecimal?

    public var skills: [Skill]
    public init(_id: String, label: Label, score: BigDecimal?, skills: [Skill]) { 
        self._id = _id
        self.label = label
        self.score = score
        self.skills = skills
    }
    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case label
        case score
        case skills
    }

}
