//
// Competence.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct CompetenceModel: Codable {
    
    public var _id: String
    public var label: String
    public var score: Double
    public var skills: [SkillModel]
    
    public init(_id: String, label: String, score: Double, skills: [SkillModel]) {
        self._id = _id
        self.label = label
        self.score = score
        self.skills = skills
    }
    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case label
        case score
        case skills
    }

}
