//
// Skill.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct Skill: Codable {


    public var _id: String

    public var label: String

    /** card score for this skill &#x3D; Battle result  */
    public var score: BigDecimal?

    /** use to create unique value for battle (id1 + id2 + value) */
    public var value: Int
    public init(_id: String, label: String, score: BigDecimal?, value: Int) { 
        self._id = _id
        self.label = label
        self.score = score
        self.value = value
    }
    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case label
        case score
        case value
    }

}
